export const MAX_ATTEMPTS=6,MAX_REVISIONS=3,MAX_MODEL_CALLS=12;
export const HYPOTHESES={
 concept:{id:'H1',title:'Formula / concept misunderstanding',gap:'Formula understanding',skill:'Formula recall',intervention:'Concept explanation',resource:'Newton’s second law relates net force to acceleration: F = ma. With the same mass, a larger net force produces a larger acceleration. Explain what each symbol means before solving another problem.'},
 calculation:{id:'H2',title:'Arithmetic / calculation error',gap:'Basic calculation',skill:'Basic division',intervention:'Targeted practice',resource:'Practise three divisions without a formula first: 12 ÷ 3, 18 ÷ 6 and 20 ÷ 4. Then insert each result into a complete physics calculation.'},
 application:{id:'H3',title:'Formula application / substitution error',gap:'Formula application',skill:'Formula application',intervention:'Worked example',resource:'Write F = ma. Divide both sides by m to get a = F ÷ m. For F = 12 N and m = 3 kg, substitute a = 12 ÷ 3 = 4 m/s². Write the rearranged formula before entering numbers.'},
 units:{id:'H4',title:'Unit handling error',gap:'Acceleration units',skill:'Unit handling',intervention:'Worked example',resource:'Acceleration is measured in metres per second squared, m/s². Since 1 N = 1 kg·m/s², dividing newtons by kilograms leaves m/s². Write and cancel units alongside the numbers.'},
 interpretation:{id:'H5',title:'Question interpretation error',gap:'Identifying given and required values',skill:'Question interpretation',intervention:'Targeted practice',resource:'Before calculating, make two lines: Given: force and mass. Find: acceleration. Match each number to its unit, then choose the equation.'},
 recall:{id:'H6',title:'Formula recall difficulty',gap:'Formula recall',skill:'Formula recall',intervention:'Retrieval question',resource:'Close your notes. Write the relationship between net force, mass and acceleration, then name each symbol. Check your notes only after attempting recall.'},
 connection:{id:'H7',title:'Missing concept connection',gap:'Connecting force, mass and acceleration',skill:'Concept connection',intervention:'Worked comparison',resource:'Compare two objects with the same force but different masses. Use a = F/m for each. Explain why doubling the mass halves the acceleration when force stays fixed.'},
 distraction:{id:'S1',title:'Distraction during study',gap:'Study interruptions',skill:'Study focus',intervention:'One protected study block',resource:'Try a 15-minute block with notifications off and the phone out of reach. Pick one question before starting, then record whether you completed it.'},
 task_size:{id:'S2',title:'Task too large or unclear',gap:'Defining the first study step',skill:'Task planning',intervention:'One smaller starting step',resource:'Replace “study the chapter” with “identify the given values in one example.” Set a five-minute timer and do only that first step.'},
 prerequisite:{id:'S3',title:'Missing prerequisite',gap:'Prerequisite readiness',skill:'Prerequisites',intervention:'Prerequisite check',resource:'Try one simpler question that uses the required earlier skill. If it is difficult, review that skill before returning to the original task.'},
 difficulty:{id:'S4',title:'Task difficulty mismatch',gap:'Choosing a manageable task',skill:'Task difficulty',intervention:'An easier entry question',resource:'Begin with a solved example. Cover its next line and try that single step, then move to a similar question with fewer steps.'}
};
export const MODULES={exam:{title:'Exam Mistake Detective',description:'Investigate the cause behind an incorrect answer.',order:['concept','calculation','application','units','interpretation']},learning:{title:'Learning Failure Diagnosis',description:'Find why studying has not yet transferred to solving.',order:['recall','concept','application','interpretation','connection']},decay:{title:'Knowledge Retention Check',description:'Compare a new check with previous evidence; time alone does not prove forgetting.',order:['recall','application','calculation','units']},connection:{title:'Concept Connection Detector',description:'Check individual ideas before testing the link between them.',order:['concept','calculation','connection','application']},friction:{title:'Study Friction Check',description:'Investigate a failed session and try one small intervention.',order:['distraction','task_size','prerequisite','difficulty']}};
export const DEFAULT_QUESTION='A 2 kg object is acted upon by a net force of 10 N. Find its acceleration.';
export const DEFAULT_ATTEMPT='a = 20 m/s²';
const choice=(text,result,aliases=[])=>({text,result,aliases});
export function questions(p={force:10,mass:2}){const f=p.force,m=p.mass,a=f/m;return [
 {id:'formula',h:'concept',prompt:'Which equation relates net force F, mass m and acceleration a?',choices:[choice('F = ma','pass',['f=ma','f=m*a','f=m×a','force=mass*acceleration']),choice('F = m ÷ a','fail',['f=m/a']),choice('a = F × m','fail',['a=f*m','a=fm'])],reason:'F = ma relates the three quantities. Correct recall contradicts this narrow formula-misunderstanding hypothesis; it does not establish all conceptual knowledge.'},
 {id:'force_change',h:'concept',prompt:'For the same mass, if the net force doubles, what happens to acceleration?',choices:[choice('It doubles','pass',['doubles','double','twice']),choice('It halves','fail',['halves','half']),choice('It stays the same','fail',['same'])],reason:'With fixed mass, acceleration is proportional to net force.'},
 {id:'division',h:'calculation',prompt:`Set physics aside for a moment. What is ${f} ÷ ${m}?`,choices:[choice(String(a),'pass'),choice(String(f*m),'fail'),choice(String(m/f),'fail')].filter((x,i,v)=>v.findIndex(y=>y.text===x.text)===i),reason:`${f} ÷ ${m} = ${a}. Passing this check weakens an arithmetic explanation, not an application explanation.`},
 {id:'division_transfer',h:'calculation',prompt:'What is 18 ÷ 3?',choices:[choice('6','pass'),choice('54','fail'),choice('15','fail')],reason:'18 ÷ 3 = 6.'},
 {id:'substitution',h:'application',prompt:`Show how you applied F = ma in your original attempt, using F = ${f} N and m = ${m} kg.`,choices:[choice(`a = ${f} ÷ ${m}`,'pass',[`a=${f}/${m}`,`${f}/${m}`,`a=f/m=${f}/${m}`,`a=${a}`,'a=f/m']),choice(`a = ${f} × ${m}`,'fail',[`a=${f}*${m}`,`${f}*${m}`,`a=f*m=${f}*${m}`,`a=${f}*${m}=${f*m}`,'a=f*m']),choice(`a = ${m} ÷ ${f}`,'fail',[`a=${m}/${f}`,`a=m/f`])],reason:'To isolate a in F = ma, divide force by mass. An explicit multiplication or inverted division is direct evidence of a substitution problem.'},
 {id:'application_transfer',h:'application',prompt:'On a new question, F = 12 N and m = 3 kg. Which setup would you use to find acceleration?',choices:[choice('a = 12 ÷ 3','pass',['a=12/3','12/3','a=4','4']),choice('a = 12 × 3','fail',['a=12*3','12*3','36']),choice('a = 3 ÷ 12','fail',['a=3/12','3/12'])],reason:'The correct setup is a = F/m = 12/3. This transfer check tests application independently of the original answer.'},
 {id:'unit',h:'units',prompt:'What is the SI unit of acceleration?',choices:[choice('m/s²','pass',['m/s^2','m/s2','metres per second squared','meters per second squared']),choice('m/s','fail'),choice('N','fail')],reason:'Acceleration is measured in m/s², not velocity units (m/s) or force units (N).'},
 {id:'unit_transfer',h:'units',prompt:'If 1 N = 1 kg·m/s², what units remain after dividing N by kg?',choices:[choice('m/s²','pass',['m/s^2','m/s2']),choice('kg·m/s²','fail'),choice('kg²·m/s²','fail')],reason:'The kilogram factor cancels, leaving m/s².'},
 {id:'identify',h:'interpretation',prompt:`In the original question, what does ${m} kg represent, and what are you asked to find?`,choices:[choice('Mass; find acceleration','pass',['mass and acceleration']),choice('Force; find mass','fail'),choice('Acceleration; find force','fail')],reason:'Kilograms identify mass. The requested unknown is acceleration.'},
 {id:'identify_transfer',h:'interpretation',prompt:'A problem gives 12 N and 3 kg and asks for acceleration. Which quantities are already given?',choices:[choice('Force and mass','pass'),choice('Mass and acceleration','fail'),choice('Force and acceleration','fail')],reason:'Newtons measure force, and kilograms measure mass.'},
 {id:'recall',h:'recall',prompt:'Without looking at your notes, write Newton’s second-law equation using F, m and a.',choices:[choice('F = ma','pass',['f=ma','f=m*a','f=m×a']),choice('F = m ÷ a','fail',['f=m/a']),choice('a = F × m','fail',['a=f*m'])],reason:'The recall target is F = ma. A single unsuccessful retrieval does not prove knowledge decay.'},
 {id:'recall_second',h:'recall',prompt:'Complete the relationship from memory: net force = mass × _____.',choices:[choice('Acceleration','pass'),choice('Velocity','fail'),choice('Distance','fail')],reason:'Newton’s second law connects force with mass times acceleration.'},
 {id:'connection',h:'connection',prompt:'You know F = ma and can divide correctly. With the same net force, doubling the mass makes acceleration…',choices:[choice('Half as large','pass',['half','halves']),choice('Twice as large','fail',['double','doubles','twice']),choice('Unchanged','fail',['same'])],reason:'a = F/m connects the force law to inverse proportionality: fixed force and doubled mass produce half the acceleration.'},
 {id:'connection_transfer',h:'connection',prompt:'Object A is 2 kg and object B is 4 kg. Each experiences 8 N. Which accelerates more?',choices:[choice('A: 4 m/s²; B: 2 m/s²','pass',['a','object a']),choice('B accelerates more because it has more mass','fail',['b','object b']),choice('They accelerate equally because force is equal','fail',['equal','same'])],reason:'The same force produces different accelerations because a also depends on mass.'},
 {id:'distraction',h:'distraction',prompt:'During the failed study session, were you repeatedly interrupted by notifications, other people or switching apps?',choices:[choice('Yes, repeatedly','fail',['yes']),choice('No, I could focus','pass',['no'])],reason:'Reported repeated interruptions support investigating study friction, not an academic ability label.'},
 {id:'distraction_second',h:'distraction',prompt:'When an interruption ended, did it take time to find your place and restart the task?',choices:[choice('Yes, I kept restarting','fail',['yes']),choice('No, I resumed easily','pass',['no'])],reason:'Repeated restarts are a second self-reported observation of interruption-related friction.'},
 {id:'task_size',h:'task_size',prompt:'Could you name one concrete first step, such as identifying the given values in one question?',choices:[choice('No, the task felt too big or unclear','fail',['no']),choice('Yes, I had a small clear step','pass',['yes'])],reason:'An unclear starting step supports investigating task size.'},
 {id:'task_size_second',h:'task_size',prompt:'Was your plan a broad goal such as “finish the chapter” without smaller steps?',choices:[choice('Yes, it was one large goal','fail',['yes']),choice('No, I had smaller steps','pass',['no'])],reason:'A large unsplit task supports a planning-friction hypothesis.'},
 {id:'prerequisite',h:'prerequisite',prompt:'Did the task use an earlier skill you could not explain or perform?',choices:[choice('Yes, an earlier skill blocked me','fail',['yes']),choice('No, I knew the earlier skills','pass',['no'])],reason:'A reported missing prerequisite needs a narrower check before a learning diagnosis.'},
 {id:'prerequisite_second',h:'prerequisite',prompt:'Did a simpler example using only that earlier skill also leave you stuck?',choices:[choice('Yes, the simpler example was difficult too','fail',['yes']),choice('No, I could do that example','pass',['no'])],reason:'Difficulty on the prerequisite-only example strengthens this self-reported hypothesis.'},
 {id:'difficulty',h:'difficulty',prompt:'Could you complete the individual steps but not the whole question together?',choices:[choice('Yes, the combined task overwhelmed me','fail',['yes']),choice('No, that was not the problem','pass',['no'])],reason:'A mismatch between individual-step and whole-task performance can support a difficulty hypothesis.'},
 {id:'difficulty_second',h:'difficulty',prompt:'Did you stop because you could not manage how many steps the task required?',choices:[choice('Yes, there were too many steps at once','fail',['yes']),choice('No, I stopped for another reason','pass',['no'])],reason:'This is self-reported task friction, not a cognitive or medical assessment.'}
];}
export function parseProblem(question,attempt){const m=question.match(/(\d+(?:\.\d+)?)\s*kg\b/i),f=question.match(/(\d+(?:\.\d+)?)\s*N\b/);if(!m||!f||!/acceleration/i.test(question))throw new Error('This MVP supports net-force questions asking for acceleration, with one mass in kg and one force in N. Use the sample or change those values.');const mass=Number(m[1]),force=Number(f[1]);if(!(mass>0&&mass<=10000&&force>0&&force<=100000))throw new Error('Use a positive mass and net force within the demo range.');const n=attempt.replace(/m\s*\/\s*s(?:\^?2|²)?/ig,'').match(/[-+]?\d+(?:\.\d+)?/g),value=n?Number(n.at(-1)):null;const hasUnits=/m\s*\/\s*s(?:\^2|2|²)/i.test(attempt);return {mass,force,expected:force/mass,submitted:value,numericCorrect:value!==null&&Math.abs(value-force/mass)<1e-6,hasUnits};}
export function normalize(s){return s.toLowerCase().trim().replace(/[.!?]+$/,'').replace(/[×·]/g,'*').replace(/÷/g,'/').replace(/²/g,'^2').replace(/\s+/g,'');}
export function deterministic(q,answer,choiceIndex){if(Number.isInteger(choiceIndex)){if(choiceIndex===q.choices.length)return {classification:'uncertain',quote:answer,note:'The student explicitly chose “I’m not sure”.'};const c=q.choices[choiceIndex];if(!c)throw new Error('Invalid answer option.');return {classification:c.result,quote:answer,note:q.reason};}const n=normalize(answer);if(['idk','notsure',"idon'tknow",'unsure','unknown','?'].includes(n))return {classification:'uncertain',quote:answer,note:'The student expressed uncertainty; no mistake is inferred.'};for(const c of q.choices)if([c.text,...c.aliases].some(s=>normalize(s)===n))return {classification:c.result,quote:answer,note:q.reason};return {classification:'uncertain',quote:answer,note:'This response could not be matched reliably. A different check is needed; the app will not guess.'};}
