import {HYPOTHESES as H,MODULES,MAX_ATTEMPTS,MAX_REVISIONS,MAX_MODEL_CALLS,questions,parseProblem,DEFAULT_QUESTION,DEFAULT_ATTEMPT} from './catalog.mjs';
import {plan,interpret} from '../llm/client.mjs';
const date=()=>new Date().toISOString();
const GRAPH={START:['LOAD_STATE'],LOAD_STATE:['OBSERVE'],OBSERVE:['FORM_HYPOTHESIS','STORE'],FORM_HYPOTHESIS:['ASK_CHECK'],ASK_CHECK:['WAIT_FOR_STUDENT'],WAIT_FOR_STUDENT:['EVALUATE_EVIDENCE','STORE'],EVALUATE_EVIDENCE:['ASK_CHECK','REVISE','CONFIRM','STORE'],REVISE:['FORM_HYPOTHESIS','STORE'],CONFIRM:['WAIT'],WAIT:['REVISE','STORE'],STORE:['FINISH'],FINISH:[]};
export function move(r,state,text,tone='neutral'){if(!GRAPH[r.state]?.includes(state))throw new Error(`Blocked transition: ${r.state} → ${state}`);r.state=state;event(r,state,text,tone);}
export function event(r,type,text,tone='neutral'){r.events.push({id:crypto.randomUUID(),at:date(),state:r.state,type,text,tone});}
export function emptyProfile(id,name='Demo Student'){return {student_id:id,name,diagnostic_history:[],confirmed_gaps:[],rejected_hypotheses:[],unresolved_hypotheses:[],topics:{},tasks:[],interventions:[],last_updated:date(),revision:0};}
export function current(p){return p.diagnostic_history.at(-1)||null;}
export function refreshProfile(p){const topics={};for(const r of p.diagnostic_history){for(const e of r.evidence){const skill=H[e.hypothesis].skill;const t=topics[skill]??={skill,checks:[],status:'Not checked'};t.checks.push({result:e.result,at:e.at,run_id:r.id});t.status=e.result==='pass'?'Demonstrated on latest check':e.result==='fail'?'Needs investigation':'Uncertain';}}
 p.topics=topics;p.rejected_hypotheses=p.diagnostic_history.flatMap(r=>r.rejected.map(x=>({...x,run_id:r.id})));
 p.unresolved_hypotheses=p.diagnostic_history.filter(r=>!['confirmed','no_gap_observed'].includes(r.outcome)).map(r=>({run_id:r.id,hypothesis:r.hypothesis,status:r.outcome||r.state,at:r.updated_at||r.created_at}));p.last_updated=date();
 for(const gap of p.confirmed_gaps){const matches=Object.values(topics).find(t=>t.skill===H[gap.hypothesis].skill);const gapIndex=p.diagnostic_history.findIndex(r=>r.id===gap.run_id);const newer=(matches?.checks||[]).filter(c=>p.diagnostic_history.findIndex(r=>r.id===c.run_id)>gapIndex);if(newer.length>=2&&newer.slice(-2).every(c=>c.result==='pass'))gap.status='Improving — recheck later';}
}
function allowedOrder(r){return MODULES[r.module].order;}
function available(r,h){return questions(r.problem).filter(q=>q.h===h&&!r.evidence.some(e=>e.question_id===q.id)&&!(q.id==='formula'&&r.evidence.some(e=>e.hypothesis==='recall'&&e.result==='pass')));}
function confidence(r){const e=r.evidence.filter(e=>e.hypothesis===r.hypothesis);return e.filter(e=>e.result==='fail').length>=2?'Medium':e.some(e=>e.result==='fail')?'Low':'Not established';}
export function stop(r,outcome='insufficient',text='Evidence insufficient — safe stop. I don’t have enough evidence to confidently identify the cause yet.') {r.outcome=outcome;r.question=null;r.confidence=outcome==='confirmed'?confidence(r):'Not established';move(r,'STORE',text,outcome==='confirmed'?'success':'warning');move(r,'FINISH','Investigation complete. Evidence and confirmation are stored separately.');r.updated_at=date();}
async function ask(env,r,eligible,isRevision=false){const chosen=await plan(env,r,eligible);if(chosen.reason)event(r,'FALLBACK',chosen.reason,'warning');const h=chosen.q.h;if(isRevision){r.revisions++;event(r,`REVISION ${r.revisions}/${MAX_REVISIONS}`,`Investigate ${H[h].title.toLowerCase()} instead. Evidence determines the next check.`,'revision');move(r,'FORM_HYPOTHESIS',`${H[h].id} — ${H[h].title}`);}if(r.hypothesis===null)event(r,'HYPOTHESIS SELECTED',`${H[h].id} — ${H[h].title}. Selected for investigation, not accepted as a diagnosis.`);r.hypothesis=h;if(!r.visited.includes(h))r.visited.push(h);r.question={id:chosen.q.id,prompt:chosen.q.prompt,choices:chosen.q.choices.map(c=>c.text),generated_wording:chosen.wording||null,source:chosen.source};move(r,'ASK_CHECK',chosen.q.prompt);move(r,'WAIT_FOR_STUDENT','Awaiting an actual student response. No evidence is inferred from silence.');r.confidence=confidence(r);}
async function revise(env,r){if(r.attempts>=MAX_ATTEMPTS){stop(r);return;}if(r.revisions>=MAX_REVISIONS){stop(r,'insufficient','Revision limit reached — safe stop. No unsupported diagnosis will be manufactured.');return;}const hs=allowedOrder(r).filter(h=>!r.visited.includes(h));if(!hs.length){stop(r,'no_gap_observed','The available checks did not establish a consistent, accepted learning gap. Correct checks do not prove overall mastery.');return;}move(r,'REVISE','Current explanation is unsupported, contradicted or rejected.');const eligible=hs.filter(h=>h!=='connection'||['concept','calculation'].every(c=>r.evidence.some(e=>e.hypothesis===c&&e.result==='pass'))).flatMap(h=>available(r,h).slice(0,1));if(!eligible.length){stop(r);return;}await ask(env,r,eligible,true);}
export async function start(p,env,input){if(current(p)&&current(p).state!=='FINISH')throw new Error('Finish or stop the current investigation before starting another.');const module=MODULES[input.module]?input.module:'exam',mode=['demo','live','practice'].includes(input.mode)?input.mode:'practice';const question=String(input.question||DEFAULT_QUESTION).trim(),attempt=String(input.attempt||DEFAULT_ATTEMPT).trim();if(question.length>2500||attempt.length>1500)throw new Error('Please shorten the question or attempt.');const problem=module==='friction'?{force:10,mass:2,expected:5,submitted:null,numericCorrect:false,hasUnits:false}:parseProblem(question,attempt);const r={id:crypto.randomUUID(),module,mode,state:'START',created_at:date(),input:{question,attempt},problem,attempts:0,revisions:0,model_calls:0,visited:[],hypothesis:null,evidence:[],rejected:[],events:[],question:null,confidence:'Not established',confirmation:'pending',outcome:null,demo_encounter:input.demo_encounter||0};
 move(r,'LOAD_STATE',`Loaded ${p.diagnostic_history.length} earlier investigation(s).`);
 let first=MODULES[module].order[0];const previous=p.confirmed_gaps.filter(g=>MODULES[module].order.includes(g.hypothesis)&&g.status==='Active').at(-1);const unresolved=p.unresolved_hypotheses.filter(g=>MODULES[module].order.includes(g.hypothesis)).at(-1);
 if(!input.ignoreMemory&&(previous||unresolved)){first=(previous||unresolved).hypothesis;r.memory={gap:previous?H[previous.hypothesis].gap:null,rejected:p.rejected_hypotheses.slice(-3).map(x=>H[x.hypothesis].title),next:H[first].title};event(r,'MEMORY LOADED',`Previous ${previous?'confirmed gap':'unresolved hypothesis'}: ${H[first].gap}. Start with a targeted ${H[first].skill.toLowerCase()} check. Old conclusions remain provisional.`,'memory');}
 if(module==='connection')first='concept'; // Component checks precede the connection check.
 if(module==='exam'&&problem.numericCorrect&&!problem.hasUnits&&!r.memory)first='units';
 move(r,'OBSERVE',module==='friction'?'A failed study session was reported. Investigate the conditions before suggesting an intervention.':problem.submitted===null?'The attempted answer could not be verified numerically. Investigate without assuming an arithmetic error.':problem.numericCorrect?'The numerical answer matches F/m. Check reasoning or units before inferring any difficulty.':`The attempted acceleration (${problem.submitted}) differs from F/m. This observation does not establish why.`);
 p.diagnostic_history.push(r);
 if(module==='exam'&&problem.numericCorrect&&problem.hasUnits&&!r.memory){stop(r,'no_gap_observed','The submitted answer matches the reviewed result and units. No error was established; use a different attempt or a learning-diagnosis module.');refreshProfile(p);return r;}
 move(r,'FORM_HYPOTHESIS','Select one testable possibility from the observations and permitted causes.');const eligible=mode==='live'&&!r.memory&&module!=='connection'?MODULES[module].order.filter(h=>h!=='connection').flatMap(h=>available(r,h).slice(0,1)):available(r,first).slice(0,1);await ask(env,r,eligible);refreshProfile(p);return r;}
export async function answer(p,env,input){const r=current(p);if(!r||r.state!=='WAIT_FOR_STUDENT')throw new Error('This session is not waiting for an answer.');if(input.question_id!==r.question.id)throw new Error('That question has already been answered or changed. Reload the current check.');const q=questions(r.problem).find(q=>q.id===r.question.id);let text=String(input.answer||'').trim();const choice=Number.isInteger(input.choice)?input.choice:undefined;if(choice!==undefined){if(choice<0||choice>q.choices.length)throw new Error('Invalid answer choice.');text=choice===q.choices.length?'I’m not sure':q.choices[choice].text;}if(!text||text.length>1000)throw new Error('Enter an answer between 1 and 1,000 characters.');if(r.attempts>=MAX_ATTEMPTS)throw new Error('The diagnostic limit has already been reached.');r.attempts++;
 event(r,r.mode==='demo'?'SCRIPTED STUDENT RESPONSE':'STUDENT RESPONSE',text);move(r,'EVALUATE_EVIDENCE','Compare the response with the checked skill, not with a guessed diagnosis.');const result=await interpret(env,r,q,text,choice);if(result.reason)event(r,'FALLBACK',result.reason,'warning');const e={id:crypto.randomUUID(),at:date(),question_id:q.id,hypothesis:r.hypothesis,question:q.prompt,response:text,result:result.classification,quote:result.quote,note:result.note,source:result.source};r.evidence.push(e);const priorCheck=p.topics[H[r.hypothesis].skill]?.checks?.at(-1);if(priorCheck&&priorCheck.run_id!==r.id&&priorCheck.result==='pass'&&result.classification==='fail')event(r,'RETENTION SIGNAL','A previous check of this skill was correct, but this response was not. Investigate the change; this does not prove forgetting or its cause.','warning');event(r,'EVIDENCE',result.note,result.classification==='pass'?'success':result.classification==='fail'?'warning':'neutral');
 const matching=r.evidence.filter(e=>e.hypothesis===r.hypothesis),fails=matching.filter(e=>e.result==='fail').length,passes=matching.filter(e=>e.result==='pass').length;r.confidence=confidence(r);
 if(result.classification==='pass'){
  if(passes===1){r.rejected.push({hypothesis:r.hypothesis,at:date(),reason:q.id==='formula'?'Formula recalled correctly. Broad concept understanding has not been established.':result.note});event(r,`${H[r.hypothesis].id} CONTRADICTED`,q.id==='division'?'Arithmetic passed. The calculation explanation is weakened; incorrect formula application is still possible.':q.id==='formula'?'Initial hypothesis rejected for formula recall: student correctly identified F = ma.':'The checked skill was demonstrated. Do not force the current hypothesis.','rejected');}
  if(fails)event(r,'CONFLICTING EVIDENCE','Correct and incorrect observations coexist. Retain both; no confident diagnosis.','warning');
  const prior=p.confirmed_gaps.some(g=>g.hypothesis===r.hypothesis&&g.status==='Active');const more=available(r,r.hypothesis);
  if(prior&&passes===1&&more.length&&r.attempts<MAX_ATTEMPTS){await ask(env,r,more.slice(0,1));}else{await revise(env,r);}
 }else if(fails>=2&&passes===0){
  if(r.hypothesis==='connection'&&!['concept','calculation'].every(h=>r.evidence.some(e=>e.hypothesis===h&&e.result==='pass'))){stop(r);}
  else{move(r,'CONFIRM',`${H[r.hypothesis].gap} is the most supported explanation so far. Evidence strength: medium; this is not certainty.`,'success');move(r,'WAIT','Does this diagnosis match what you found difficult? Awaiting Yes, No or Not sure.');r.question=null;}
 }else{if(result.classification==='uncertain')event(r,'INSUFFICIENT EVIDENCE','An incomplete or unclear response is not an incorrect answer.','warning');const more=available(r,r.hypothesis);if(more.length&&r.attempts<MAX_ATTEMPTS)await ask(env,r,more.slice(0,1));else await revise(env,r);}
 r.updated_at=date();refreshProfile(p);return r;}
export async function confirmDiagnosis(p,env,value,scripted=false){const r=current(p);if(!r||r.state!=='WAIT')throw new Error('There is no diagnosis waiting for confirmation.');if(!['yes','no','unsure'].includes(value))throw new Error('Choose Yes, No or Not sure.');r.confirmation=value;event(r,scripted?'SCRIPTED CONFIRMATION':'STUDENT CONFIRMATION',value==='yes'?'YES — student agrees. Agreement does not turn limited evidence into certainty.':value==='no'?'NO — diagnosis rejected by the learner.':'NOT SURE — diagnosis remains unconfirmed.',value==='yes'?'success':'warning');
 if(value==='yes'){const gap={id:crypto.randomUUID(),hypothesis:r.hypothesis,label:H[r.hypothesis].gap,confidence:'Medium',status:'Active',at:date(),run_id:r.id,evidence_ids:r.evidence.filter(e=>e.hypothesis===r.hypothesis&&e.result==='fail').map(e=>e.id)};p.confirmed_gaps.push(gap);p.interventions.push({id:crypto.randomUUID(),run_id:r.id,hypothesis:r.hypothesis,title:H[r.hypothesis].intervention,text:H[r.hypothesis].resource,outcome:'Not tried',at:date()});stop(r,'confirmed',`Student profile updated: ${gap.label}. A targeted intervention is now available.`);}else if(value==='no'){r.rejected.push({hypothesis:r.hypothesis,at:date(),reason:'Student rejected the proposed diagnosis.'});await revise(env,r);}else stop(r,'unconfirmed','Student is unsure. Store an unconfirmed hypothesis without recommending an intervention.');refreshProfile(p);return r;}
export async function demoStep(p,env){const r=current(p);if(!r)return start(p,env,{module:'exam',mode:'demo',ignoreMemory:true,demo_encounter:1});if(r.mode!=='demo')throw new Error('Demo controls only work on a Demo Mode session.');if(r.demo_encounter===2)return r;
 if(r.state==='WAIT_FOR_STUDENT'){const answers={formula:0,force_change:0,division:0,substitution:1,application_transfer:1};return answer(p,env,{question_id:r.question.id,choice:answers[r.question.id]??0});}
 if(r.state==='WAIT')return confirmDiagnosis(p,env,'yes',true);
 if(r.state==='FINISH')return start(p,env,{module:'exam',mode:'demo',demo_encounter:2});return r;}
export function dashboard(p){const gaps=p.confirmed_gaps.filter(g=>g.status==='Active');const upcoming=p.tasks.filter(t=>!t.done).sort((a,b)=>a.due.localeCompare(b.due));const last=current(p);let action=last&&last.state!=='FINISH'?'Resume the current diagnostic check.':gaps.length?`Check ${gaps.at(-1).label.toLowerCase()} on a new question.`:p.unresolved_hypotheses.length?'Revisit the most recent unresolved hypothesis.':'Start with one question you lost marks on.';if(upcoming[0])action+=` Upcoming task: ${upcoming[0].title}.`;return {active_gaps:gaps,upcoming,recent_mistakes:p.diagnostic_history.flatMap(r=>r.evidence.filter(e=>e.result==='fail').map(e=>({...e,run_id:r.id}))).slice(-5).reverse(),recommended:action};}
export {H, MODULES,MAX_ATTEMPTS,MAX_REVISIONS,MAX_MODEL_CALLS,DEFAULT_QUESTION,DEFAULT_ATTEMPT};
