import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import worker from '../backend/api/app.mjs';import {adapter} from '../backend/state/database.mjs';
const migration=fs.readFileSync('backend/db/migrations/001_initial.sql','utf8');
function setup(file=':memory:'){const sql=new DatabaseSync(file);sql.exec(migration);return {sql,env:{DB:adapter(sql),LOCAL:true}};}
const req=(url,cookie,body)=>new Request('http://localhost'+url,{method:body?'POST':'GET',headers:{Cookie:cookie||'','Content-Type':'application/json',Origin:'http://localhost'},...(body?{body:JSON.stringify(body)}:{})});
test('API enforces idempotency, profile separation, persistent resume and concurrent updates',async()=>{const {sql,env}=setup();let res=await worker.fetch(req('/api/profile'),env);const cookie=res.headers.get('Set-Cookie').split(';')[0];let s=await res.json();const start={kind:'start',revision:s.profile.revision,request_id:'start-1'};res=await worker.fetch(req('/api/action',cookie,start),env);assert.equal(res.status,200);s=await res.json();assert.equal(s.run.question.id,'formula');res=await worker.fetch(req('/api/action',cookie,start),env);assert.equal(res.status,200);assert.equal((await res.json()).profile.diagnostic_history.length,1);const b={kind:'answer',revision:s.profile.revision,request_id:'answer-1',question_id:'formula',answer:'F = ma'};const responses=await Promise.all([worker.fetch(req('/api/action',cookie,b),env),worker.fetch(req('/api/action',cookie,{...b,request_id:'answer-2'}),env)]);assert.deepEqual(responses.map(x=>x.status).sort(),[200,409]);s=await (await worker.fetch(req('/api/profile',cookie),env)).json();assert.equal(s.run.attempts,1);assert.equal(s.run.question.id,'division');const demo=await (await worker.fetch(req('/api/profile?profile=demo',cookie),env)).json();assert.equal(demo.profile.diagnostic_history.length,0);const other=await (await worker.fetch(req('/api/profile'),env)).json();assert.equal(other.profile.diagnostic_history.length,0);assert.equal((await worker.fetch(new Request('http://localhost/api/action',{method:'POST',headers:{Origin:'http://evil.invalid','Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(b)}),env)).status,403);sql.close();});
test('database survives process-equivalent reopen',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cognix-test-')),file=path.join(dir,'db.sqlite');const {sql,env}=setup(file);let res=await worker.fetch(req('/api/profile'),env);const cookie=res.headers.get('Set-Cookie').split(';')[0];const first=await res.json();await worker.fetch(req('/api/action',cookie,{kind:'start',request_id:'first',revision:first.profile.revision}),env);sql.close();const reopen=new DatabaseSync(file);const resumed=await (await worker.fetch(req('/api/profile',cookie),{DB:adapter(reopen),LOCAL:true})).json();assert.equal(resumed.run.state,'WAIT_FOR_STUDENT');assert.equal(resumed.run.question.id,'formula');reopen.close();fs.rmSync(dir,{recursive:true});});
test('database failure is recoverable and never claims an answer saved',async()=>{const result=await worker.fetch(req('/api/profile'),{DB:{prepare(){throw new Error('storage down')}}});assert.equal(result.status,503);assert.match((await result.json()).error,/not been confirmed as saved/);});
test('demo API reaches second encounter, persists evidence, then accepts independent answers',async()=>{const {sql,env}=setup();let res=await worker.fetch(req('/api/profile?profile=demo'),env);const cookie=res.headers.get('Set-Cookie').split(';')[0];let s=await res.json();async function action(body){const response=await worker.fetch(req('/api/action?profile=demo',cookie,{...body,revision:s.profile.revision,request_id:crypto.randomUUID()}),env);assert.equal(response.status,200);s=await response.json();}await action({kind:'demo_start'});for(let i=0;i<6;i++)await action({kind:'demo_step'});assert.equal(s.run.demo_encounter,2);assert.equal(s.run.question.id,'substitution');assert.equal(s.profile.confirmed_gaps[0].label,'Formula application');assert.equal(s.profile.interventions.length,1);assert.equal(s.profile.diagnostic_history[0].revisions,2);await action({kind:'answer',question_id:s.run.question.id,choice:0});assert.equal(s.run.question.id,'application_transfer');sql.close();});
